# Generated by Django 4.2.5 on 2023-09-14 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_product_price_deliveryrequest'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('can_view_all_products', 'Can view all products'), ('can_add_product', 'Can add product'), ('can_edit_product', 'Can edit product'), ('can_delete_product', 'Can delete product'), ('can_make_delivery_requests', 'Can make delivery requests'), ('can_execute_delivery_requests', 'Can execute delivery requests')]},
        ),
    ]
