services:
  db:
    image: postgres:15.0
    environment:
      POSTGRES_USER: atom
      POSTGRES_PASSWORD: atom
      PGDATA: /data/postgres
    volumes:
      - db:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - db
    restart: unless-stopped

  app:
    build: .
    container_name: delivery_system_app
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/purchasedata
      - SPRING_DATASOURCE_USERNAME=atom
      - SPRING_DATASOURCE_PASSWORD=atom
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    networks:
      - db

  django:
    build: ../eShop_backend
    container_name: delivery_system_django
    depends_on:
      - db
    ports:
      - "8000:8000"
    volumes:
      - ../eShop_backend/db.sqlite3:/code/db.sqlite3
    networks:
      - db

  react:
    build: ../eShop-frontend
    container_name: delivery_system_react
    depends_on:
      - django
    ports:
      - "5173:5173"
    networks:
      - db
networks:
  db:
    driver: bridge

volumes:
  db:
